on:
  release:
    types:
      - published
    workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: installing dependencies
        run: npm i

      - name: getting vsce
        run: npm i -g vsce

      - name: publishing
        run: vsce publish -p ${{ secrets.pat }}